const bodyParser = require('body-parser');
const express = require('express');
const connection = require('./conf.js');
const app = express();
const port = 8080;
const cors = require('cors');

app.use(cors({ origin: '*' }));

// Support JSON-encoded bodies
app.use(bodyParser.json());
// Support URL-encoded bodies
app.use(bodyParser.urlencoded({
  extended: true
}));

// test sample---> './sample_card.json

// ROUTE GET cards to get ids, names, images 
// and descriptions of cards
app.get('/cards/', (request, response) => {
  connection.query('SELECT id, name, image, description FROM card', (error, results) =>{
    if (error) {
      response.status(500).send('Erreur lors de la récupération des cartes');
    }
    response.status(200).send(results);
  });
});

// ROUTE card
app.route('/card/')
  //POST 
  .post((request, response) => {
    const data = request.body;
    //Set objects to insert into tables
    const dataContentVideos = data.videos;
    const dataContentQuestions = data.questions;
    const cardData = data.card;
    //Insert table card content
    connection.query('INSERT INTO card SET ?', cardData, (error, resultCard) => {
      if (error) {
        console.log(error);
        response.status(500).send("Erreur lors de l'ajout de la carte");
      }
      //Posting videos(array of objects) putting for each   
      // the id generated by the insert in table card
      dataContentVideos.map(dataContentVideo => {
        connection.query(`INSERT INTO videos SET id_card ='${resultCard.insertId}', ?`,
        dataContentVideo, (error, resultVideo) => {
          if (error) {
            console.log(error);
            response.status(500).send("Erreur lors de l'ajout de la vidéo");
          }
        });
      });
      //Inserting questions one by one 
      // getting each id in resultResource
      dataContentQuestions.map(dataContentQuestion => {
        // Getting resources object of question in a let
        let resources = dataContentQuestion.resources;
        connection.query(`INSERT INTO questions SET 
        id_card ='${resultCard.insertId}',
        number_question = '${dataContentQuestion.number_question}',
        text_question = "${dataContentQuestion.text_question}",
        image_question = "${dataContentQuestion.image_question}",
        type_response = '${dataContentQuestion.type_response}',
        has_comment = '${dataContentQuestion.has_comment}'`,
        (error, resultQuestion) => {
            if (error) {
              console.log(error);
              response.status(500).send("Erreur lors de l'ajout de la question");
            }
            // for a question, inserting corresponding resources
            // with question id resultQuestion
            resources.map((resource) => {
              connection.query(`INSERT INTO resources SET 
              id_question='${resultQuestion.insertId}', ?`,
              resource, (error, resultResource) => {
                if (error) {
                  console.log(error);
                  response.status(500).send("Erreur lors de l'ajout de la resource");
                }
              });
            });
        });
      });
      response.sendStatus(200);
    });
  })
  //GET 
  .get((request, response) => {
    // fetch : axios.get('http://localhost:8080/card/', { params: { id: 1 } })
    let idCard = request.query.id;
    connection.query(`SELECT * FROM card WHERE id=${idCard}`, (error, result) => {
      if (error) {
        console.log(error);
        response.status(500).send("Erreur lors de la récupération de la carte");
      }
      connection.query(`SELECT * FROM videos WHERE id_card=${idCard}`, 
      (error, resultVideos) => {
        if (error) {
          console.log(error);
          response.status(500).send("Erreur lors de la récupération des vidéos");
        }
        connection.query(`SELECT * FROM questions WHERE id_card=${idCard}`, (error, resultQuestions) => {
          if (error) {
            console.log(error);
            response.status(500).send("Erreur lors de la récupération des questions");
          }
          //Getting questions'ids in an array
          const idQuestions = resultQuestions.map(question => question.id); 
          //Used to get associated resources
          connection.query(`SELECT * FROM resources WHERE id_question IN ('${idQuestions}')`,
          (error, resultResources) => {
            if (error) {
              console.log(error);
              response.status(500).send("Erreur lors de la récupération des ressources");
            }
            // Redefining resultQuestions'content inserting resources
            const questions = resultQuestions.map(question => {
            return  {
              number_question : question.number_question,
              text_question : question.text_question,
              image_question : question.image_question,
              type_response : question.type_response,
              has_comment : question.has_comment,
              resources : resultResources.filter(resource => resource.id_question === question.id)
            }
          });
            //Building data to send : 
            //{card : {}, videos : [{}, {}, {}], questions : [{resources:[{},{}]},...]...}
            const data = {
              card: result[0],
              videos: resultVideos,
              questions: questions
            };
            response.status(200).send(data);
          }) 
        });
      });
    });
  })
  //DELETE (id )
  .delete((request, response) => {
    let idCard = request.query.id
    // Deleteing card content with id
    // and others related tables on cascade
    connection.query(`DELETE FROM card WHERE id=${idCard}`, (error, result) => {
      if (error) {
        console.log(error);
        response.status(500).send("Erreur lors de la suppression de la carte");
      }
      response.sendStatus(200);
    });
  })
  // PUT (id)
  .put((request, response) => {
    const data = request.body;
    let idCard = request.query.id;
    // building data from request
    const dataContentVideos = data.videos;
    const dataContentQuestions = data.questions;
    const cardData = data.card;
    //Upadtin card with its id
    connection.query(`UPDATE card SET ? WHERE id=${idCard}`, 
    cardData, (error, resultCard) => {
      if (error) {
        console.log(error);
        response.status(500).send("Erreur lors de la modification de la carte");
      }
      dataContentVideos.map(dataContentVideo => {
        connection.query(`UPDATE videos SET ? WHERE id_card ='${idCard}' AND
        type_video='${dataContentVideo.type_video}'`, 
        dataContentVideo, (error, resultVideo) => {
          if (error) {
            console.log(error);
            response.status(500).send("Erreur lors de la modification de la vidéo");
          }
        });
      });
      // Deleting old questions and resources (ON DELETE CASCADE)
      connection.query(`DELETE FROM questions WHERE id_card=${idCard}`, 
      (error, result) => {
        if (error) {
          console.log(error);
          response.status(500).send("Erreur lors de la suppression des anciennes questions et ressources");
        }
      });
      // Inserting new questions and resources
      dataContentQuestions.map(dataContentQuestion => {
        let resources = dataContentQuestion.resources;
        connection.query(`INSERT INTO questions SET
          id_card ='${idCard}',
          number_question = '${dataContentQuestion.number_question}',
          text_question = "${dataContentQuestion.text_question}",
          image_question = "${dataContentQuestion.image_question}",
          type_response = '${dataContentQuestion.type_response}',
          has_comment = '${dataContentQuestion.has_comment}'`,
          (error, resultQuestion) => {
            if (error) {
              console.log(error);
              response.status(500).send("Erreur lors de l'ajout de la question");
            }
            resources.map((resource) => {
              connection.query(`INSERT INTO resources SET id_question='${resultQuestion.insertId}', ?`,
                resource, (error, resultResource) => {
                  if (error) {
                    console.log(error);
                    response.status(500).send("Erreur lors de l'ajout de la resource");
                  }
                });
            });
          });
        });
      });
    response.sendStatus(200);
  });

  app.get('/test/',(req, res) => {
    connection.query('SELECT * FROM `intwetion`.`card` INNER JOIN `intwetion`.`questions` on `questions`.`id_card` = `card`.`id` INNER JOIN `resources` ON `resources`.`id_question`= `questions`.`id`;', (err, resu)=>{
      if (err) {
        res.status(500).send('Erreur!');
      }
      res.json(resu);
    })
  });
app.listen(port, (req, res) => {
  console.log(`listening on port ${port}`);
});
